name: Docker Build and Publish
on: [workflow_dispatch]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build And Push - serve-piper-tts Docker image
        run: |
          docker build . --tag ghcr.io/arunk140/serve-piper-tts:latest
          docker push ghcr.io/arunk140/serve-piper-tts:latest
